Fix unused function compile issues
Integrating DataSketches CPC to Impala, when compiling with -ASan parameter, the following error is displayed:
...
In file included from /home/impdev/Impala/be/src/exprs/datasketches-common.cc:22:
In file included from /home/impdev/Impala/be/src/thirdparty/datasketches/cpc_sketch.hpp:309:
In file included from /home/impdev/Impala/be/src/thirdparty/datasketches/cpc_sketch_impl.hpp:32:
/home/impdev/Impala/be/src/thirdparty/datasketches/icon_estimator.hpp:248:15: error: unused function 'compute_icon_estimate' [-Werror,-Wunused-function]
static double compute_icon_estimate(uint8_t lg_k, uint64_t c) {
              ^
1 error generated.